- apps/pink/src/pages/index.astro
- fixes broken links
fixes #28 
✅
> fix: broken link

- README.md
Add a list of supported browsers
Manual
Yep :)
> chore: add supported browsers

- README.md
- packages/icons/README.md
- packages/ui/README.md
"Help us understand your motivation by explaining why you decided to make this change." -- I find it is important to ensure that all commands in a repository readme run without any modifications necessary. This facilitates allowing beginners to use your library / framework.
> updated npm install declaration in documentation

- apps/pink/src/components/layout/SideNav.astro
- apps/pink/src/layouts/Layout.astro
Adds persistent sidenav collapsible state between navigation
Manual
N/A
Yes
> Feat: Persistent sidenav

- apps/pink/src/components/CodePreview.svelte
Improves legibility of selected code on dark theme, by changing the selection color
Manual
Closes #49 
Yes
> Fix: Improve text selection color

- apps/pink/src/components/homepage/HeroAnimation.svelte
- apps/pink/src/components/homepage/TryItOut.svelte
- apps/pink/src/pages/index.astro
Fixes a bug in which the active tab inside the sticky tabs was wrong.
Manual
Closes #38 
Yes
> Fix: sticky tabs active session

- apps/pink/src/components/layout/NavAccordion.astro
- apps/pink/src/components/layout/SideNav.astro
- apps/pink/src/layouts/Layout.astro
Removes an unnecessary event handler on collapsible-wrappers, which was creating unexpected behaviour throughout the site.
Manual
Closes #36 
Yes
> Fix: Collapsible clicks

- apps/pink/src/components/homepage/HeroAnimation.svelte
- apps/pink/src/pages/index.astro
Adds a global rule for prefers-reduced-motion
Manual
N/A
Yes
> Refactor: Global reduced motion rule

- apps/pink/src/components/defaults/TableCol.astro
- apps/pink/src/layouts/Layout.astro
Adds styling to table-col to prevent narrow columns
Manual
- #33 
Yes
> Fix: mobile table styling

- apps/pink/src/components/CodePreview.svelte
- apps/pink/src/pages/index.astro
- packages/ui/src/7-components/_code-panel.scss
- Fixes inconsistent code panel styling across themes
Manual
Closes #37 
Yes
> Fix: code panel styling

- apps/pink/src/layouts/Layout.astro
- add google analytics to the pink design website
- manually
✅
> feat(pink): add ga

- apps/pink/src/pages/foundations/responsive.mdx
It fixes issue #64  which is a typo in the Responsive foundations docs
(Write your test plan here. If you changed any code, please provide us with clear instructions on how you verified your changes work.)
Fixes #64 
Yes, I have.
> docs: Fix Typo in Responsive Foundations doc

- CONTRIBUTING.md
When we visit https://github.com/appwrite/pink/blob/main/CONTRIBUTING.md made the changes in CONTRIBUTING.md's setup guidelines
#71
Yes
> Updated the setup guidelines in contributing.md

- packages/icons/README.md
- packages/ui/README.md
> fix: npm image preview

- apps/pink/src/components/BrandIcons.astro
- apps/pink/src/components/Icons.astro
- apps/pink/src/pages/foundations/icons.mdx
Displays the exported icons on the docs, instead of just linking to heroicons.
Manual
Closes #76 
Yes
> feat: display exported icons

- apps/pink/src/components/IconContainer.astro
- apps/pink/src/components/Icons.astro
This pull request includes the following changes:
* Added copy icons feature
* Refactored Icons.astro component code
This PR adds a new feature and improves the code of an existing component. Specifically, it adds copy icons feature which will help user to copy icons by clicking them. It also refactors the Icons.astro component code to improve its performance and readability.
I tested the code with the help of `npm run test` it shows no error all things are clear.
No related PR found
(Yes)
> Added copy icons feature & refactored Icons.astro component code

- apps/pink/public/prismjs.css
- apps/pink/src/components/Preview.astro
- apps/pink/src/components/Search.svelte
- apps/pink/src/components/homepage/TryItOut.svelte
- apps/pink/src/layouts/Layout.astro
- apps/pink/src/pages/components/upload-file-box.mdx
- apps/pink/src/pages/index.astro
- packages/ui/src/6-elements/_box.scss
- packages/ui/src/7-components/_upload-file-box.scss
- Adds animation to file upload box
Manual
N/A
Yes
> Feat: file upload box animation

- apps/pink/src/pages/getting-started.mdx
- apps/pink/src/pages/index.astro
Fixes the npm install command to run in both Bash and PowerShell.
Tested the Astro app locally
Fixes #89 
Yes
> Fix npm command to run on both Bash and PowerShell

- apps/pink/src/layouts/Layout.astro
(Provide a description of what this PR does.)
(Write your test plan here. If you changed any code, please provide us with clear instructions on how you verified your changes work.)
(If this PR is related to any other PR or resolves any issue or related to any issue link all related PR and issues here.)
(Write your answer here.)
> feat: remove google tag manager

- .github/workflows/alt-text-image.yml
adding GitHub's alt-text accessibility bot .yml file
> feature: alt-text-image.yml

- apps/pink/src/components/CodeEditor.svelte
(Provide a description of what this PR does.)
(Write your test plan here. If you changed any code, please provide us with clear instructions on how you verified your changes work.)
(If this PR is related to any other PR or resolves any issue or related to any issue link all related PR and issues here.)
(Write your answer here.)
> Style fixes 1

- apps/pink/src/components/CodeEditor.svelte
- packages/ui/src/8-grids/_wizard.scss
> Wizard style fix mobile

- packages/ui/src/1-css-variables/_colors.scss
- packages/ui/src/7-components/_secondary-tabs.scss
- packages/ui/src/7-components/_tabs.scss
(Provide a description of what this PR does.)
(Write your test plan here. If you changed any code, please provide us with clear instructions on how you verified your changes work.)
(If this PR is related to any other PR or resolves any issue or related to any issue link all related PR and issues here.)
(Write your answer here.)
> Tabs refactor

- apps/kitchensink/vite.config.js
- apps/kitchensink/wizard-with-modal-empty.html
- apps/kitchensink/wizard-with-modal.html
- packages/ui/src/6-elements/_button.scss
- packages/ui/src/6-elements/_table.scss
- packages/ui/src/7-components/_modal.scss
- packages/ui/src/_9-utilities.scss
- New type of Modal
- Two demos on kitchensync
> Modal full page in mobile

- packages/ui/src/8-grids/_grid-1-1.scss
- update to new value of dvh instead vh and old webkit value
> - fix full page in login page

- .changeset/red-camels-pretend.md
- apps/kitchensink/user.html
- package-lock.json
- packages/ui/src/_9-utilities.scss
This is only update of HTML demo fo Console
> Demo mulitiple input field layout

- packages/ui/src/1-css-variables/_colors.scss
- update color-type-10 according to the design system
> Update colors type-10

- .changeset/six-rabbits-obey.md
- apps/kitchensink/create-org-modal.html
- apps/kitchensink/vite.config.js
- apps/pink/src/pages/elements/list.mdx
- packages/ui/src/7-components/_list.scss
- new type of on-order list
- new demo of the organization modal
- Update list page of Pink Design
> Create organization Modal

- apps/pink/src/pages/components/alert.mdx
- packages/ui/src/7-components/_alert.scss
- Update style
- Update Pni demo x button (remove special size)
- Review with Chen
> Update alert alignment logic

- apps/pink/src/pages/foundations/colors.mdx
- packages/ui/src/1-css-variables/_colors.scss
- packages/ui/src/2-resets/_typography.scss
- Added new mint color
- Update text selection style
> Update text selection style

- apps/kitchensink/layout-1-2.html
- apps/pink/src/pages/components/avatar.mdx
- packages/ui/src/6-elements/_avatar.scss
- Remove state class ```is-with-border``` which isn't doing anything
> Group Avatars - delete unnecessary state class

- .changeset/angry-coins-visit.md
- packages/ui/src/8-grids/_wizard-secondary.scss
> Wizard Secondary

- .changeset/proud-ducks-suffer.md
- apps/kitchensink/startups-program.html
- apps/kitchensink/vite.config.js
- package-lock.json
- packages/ui/src/8-grids/_grid-2-1.scss
- packages/ui/src/8-grids/_index.scss
-Create demo page with section
- new grid-2-1
> Startup Program section

- v2/pink-sb/src/lib/link/_link.scss
> Update  -900 colors to theme based var

- v2/pink-sb/src/lib/HiddenText.svelte
- v2/pink-sb/src/lib/index.ts
- v2/pink-sb/src/stories/HiddenText.stories.svelte
> Feat hidden text

- v2/pink-sb/src/lib/Fieldset.svelte
- v2/pink-sb/src/stories/Fieldset.stories.svelte
Remove the background color of the legend
✅
> Remove fieldset legend background

- v2/pink-sb/src/themes/light.json
> Update border neutral
